function [mx28_fields,cm730_fields,ids] = darwinop_consts
mx28_fields = {
    field(0,2,'Model Number','Model number','AR'), ...
    field(0,1,'Model Number (L)','Lowest byte of model number','AR'), ...
    field(1,1,'Model Number (H)','Highest byte of model number','AR'), ...
    field(2,1,'Version of Firmware','Information on the version of firmware','AR'), ...
    field(3,1,'ID','ID of Dynamixel','ARW'), ...
    field(4,1,'Baud Rate','Baud Rate of Dynamixel','ARW'), ...
    field(5,1,'Return Delay Time','Return Delay Time','ARW'), ...
    field(6,2,'CW Angle Limit','Clockwise Angle Limit','RW'), ...
    field(6,1,'CW Angle Limit (L)','Lowest byte of clockwise Angle Limit','ARW'), ...
    field(7,1,'CW Angle Limit (H)','Highest byte of clockwise Angle Limit','ARW'), ...
    field(8,2,'CCW Angle Limit','Counterclockwise Angle Limit','RW'), ...
    field(8,1,'CCW Angle Limit (L)','Lowest byte of counterclockwise Angle Limit','ARW'), ...
    field(9,1,'CCW Angle Limit (H)','Highest byte of counterclockwise Angle Limit','ARW'), ...
    field(11,1,'the Highest Limit Temperature','Internal Limit Temperature','ARW'), ...
    field(12,1,'the Lowest Limit Voltage','Lowest Limit Voltage','ARW'), ...
    field(13,1,'the Highest Limit Voltage','Highest Limit Voltage','ARW'), ...
    field(14,2,'Max Torque','Max. Torque','ARW'), ...
    field(14,1,'Max Torque (L)','Lowest byte of Max. Torque','ARW'), ...
    field(15,1,'Max Torque (H)','Highest byte of Max. Torque','ARW'), ...
    field(16,1,'Status Return Level','Status Return Level','ARW'), ...
    field(17,1,'Alarm LED','LED for Alarm','ARW'), ...
    field(18,1,'Alarm Shutdown','Shutdown for Alarm','ARW'), ...
    field(24,1,'Torque Enable','Torque On/Off','RW'), ...
    field(25,1,'LED','LED On/Off','RW'), ...
    field(26,1,'D Gain','Derivative Gain','RW'), ...
    field(27,1,'I Gain','Integral Gain','RW'), ...
    field(28,1,'P Gain','Proportional Gain','RW'), ...
    field(30,2,'Goal Position','Goal Position','RW'), ...
    field(30,1,'Goal Position (L)','Lowest byte of Goal Position','ARW'), ...
    field(31,1,'Goal Position (H)','Highest byte of Goal Position','ARW'), ...
    field(32,2,'Moving Speed','Moving Speed','RW'), ...
    field(32,1,'Moving Speed (L)','Lowest byte of Moving Speed','ARW'), ...
    field(33,1,'Moving Speed (H)','Highest byte of Moving Speed','ARW'), ...
    field(34,2,'Torque Limit','Torque Limit','RW'), ...
    field(34,1,'Torque Limit (L)','Lowest byte of Torque Limit','ARW'), ...
    field(35,1,'Torque Limit (H)','Highest byte of Torque Limit','ARW'), ...
    field(36,2,'Present Position','Current Position','R'), ...
    field(36,1,'Present Position (L)','Lowest byte of Current Position','AR'), ...
    field(37,1,'Present Position (H)','Highest byte of Current Position','AR'), ...
    field(38,2,'Present Speed','Current Speed','R'), ...
    field(38,1,'Present Speed (L)','Lowest byte of Current Speed','AR'), ...
    field(39,1,'Present Speed (H)','Highest byte of Current Speed','AR'), ...
    field(40,2,'Present Load','Current Load','R'), ...
    field(40,1,'Present Load (L)','Lowest byte of Current Load','AR'), ...
    field(41,1,'Present Load (H)','Highest byte of Current Load','AR'), ...
    field(42,1,'Present Voltage','Current Voltage','AR'), ...
    field(43,1,'Present Temperature','Current Temperature','AR'), ...
    field(44,1,'Registered','Means if Instruction is registered','AR'), ...
    field(46,1,'Moving','Means if there is any movement','AR'), ...
    field(47,1,'Lock','Locking EEPROM','ARW'), ...
    field(48,2,'Punch','Punch','ARW'), ...
    field(48,1,'Punch (L)','Lowest byte of Punch','ARW'), ...
    field(49,1,'Punch (H)','Highest byte of Punch','ARW')
  };

cm730_fields = {
    field(0,2,'Model Number','model number','AR'), ...
    field(0,1,'Model Number (L)','model number low byte','AR'), ...
    field(1,1,'Model Number (H)','model number high byte','AR'), ...
    field(2,1,'Version of Firmware','firmware version','AR'), ...
    field(3,1,'ID','Dynamixel ID','ARW'), ...
    field(4,1,'Baud Rate','Dynamixel baud rate','ARW'), ...
    field(5,1,'Return Delay Time','Return Delay Time','ARW'), ...
    field(16,1,'Status Return Level','Status Return Level','ARW'), ...
    field(24,1,'Dynamixel Power','Dynamixel On/Off','ARW'), ...
    field(25,1,'LED Pannel','LED Pannel On/Off','RW'), ...
    field(26,2,'LED Head','LED Head','RW'), ...
    field(26,1,'LED Head (L)','LED Head low byte','ARW'), ...
    field(27,1,'LED Head (H)','LED Head high byte','ARW'), ...
    field(28,2,'LED Eye','LED Eye','RW'), ...
    field(28,1,'LED Eye (L)','LED Eye low byte','ARW'), ...
    field(29,1,'LED Eye (H)','LED Eye high byte','ARW'), ...
    field(30,1,'Button','Button status','R'), ...
    field(38,2,'Gyro Z','Gyroscope Z-axis','R'), ...
    field(38,1,'Gyro Z (L)','Gyroscope Z-axis low byte','AR'), ...
    field(39,1,'Gyro Z (H)','Gyroscope Z-axis high byte','AR'), ...
    field(40,2,'Gyro Y','Gyroscope Y-axis','R'), ...
    field(40,1,'Gyro Y (L)','Gyroscope Y-axis low byte','AR'), ...
    field(41,1,'Gyro Y (H)','Gyroscope Y-axis high byte','AR'), ...
    field(42,2,'Gyro X','Gyroscope X-axis','R'), ...
    field(42,1,'Gyro X (L)','Gyroscope X-axis low byte','AR'), ...
    field(43,1,'Gyro X (H)','Gyroscope X-axis high byte','AR'), ...
    field(44,2,'ACC X','Accelerometer X-axis','R'), ...
    field(44,1,'ACC X (L)','Accelerometer X-axis low byte','AR'), ...
    field(45,1,'ACC X (H)','Accelerometer X-axis high byte','AR'), ...
    field(46,2,'ACC Y','Accelerometer Y-axis','R'), ...
    field(46,1,'ACC Y (L)','Accelerometer Y-axis low byte','AR'), ...
    field(47,1,'ACC Y (H)','Accelerometer Y-axis high byte','AR'), ...
    field(48,2,'ACC Z','Accelerometer Z-axis','R'), ...
    field(48,1,'ACC Z (L)','Accelerometer Z-axis low byte','AR'), ...
    field(49,1,'ACC Z (H)','Accelerometer Z-axis high byte','AR'), ...
    field(50,1,'Present Voltage','Current Voltage','AR'), ...
    field(51,2,'MIC Left','Mic Left low byte','R'), ...
    field(51,1,'MIC Left (L)','Mic Left low byte','AR'), ...
    field(52,1,'MIC Left (H)','Mic Left high byte','AR'), ...
    field(53,2,'ADC 2','ADC channel 2','AR'), ...
    field(53,1,'ADC 2 (L)','ADC channel 2 low byte','AR'), ...
    field(54,1,'ADC 2 (H)','ADC channel 2 high byte','AR'), ...
    field(55,2,'ADC 3','ADC channel 3','AR'), ...
    field(55,1,'ADC 3 (L)','ADC channel 3 low byte','AR'), ...
    field(56,1,'ADC 3 (H)','ADC channel 3 high byte','AR'), ...
    field(57,2,'ADC 4','ADC channel 4','AR'), ...
    field(57,1,'ADC 4 (L)','ADC channel 4 low byte','AR'), ...
    field(58,1,'ADC 4 (H)','ADC channel 4 high byte','AR'), ...
    field(59,2,'ADC 5','ADC channel 5','AR'), ...
    field(59,1,'ADC 5 (L)','ADC channel 5 low byte','AR'), ...
    field(60,1,'ADC 5 (H)','ADC channel 5 high byte','AR'), ...
    field(61,2,'ADC 6','ADC channel 6','AR'), ...
    field(61,1,'ADC 6 (L)','ADC channel 6 low byte','AR'), ...
    field(62,1,'ADC 6 (H)','ADC channel 6 high byte','AR'), ...
    field(63,2,'ADC 7','ADC channel 7','AR'), ...
    field(63,1,'ADC 7 (L)','ADC channel 7 low byte','AR'), ...
    field(64,1,'ADC 7 (H)','ADC channel 7 high byte','AR'), ...
    field(65,2,'ADC 8','ADC channel 8','AR'), ...
    field(65,1,'ADC 8 (L)','ADC channel 8 low byte','AR'), ...
    field(66,1,'ADC 8 (H)','ADC channel 8 high byte','AR'), ...
    field(67,2,'MIC Right','Mic Right','R'), ...
    field(67,1,'MIC Right (L)','Mic Right low byte','AR'), ...
    field(68,1,'MIC Right (H)','Mic Right high byte','AR'), ...
    field(69,2,'ADC 10','ADC channel 10','AR'), ...
    field(69,1,'ADC 10 (L)','ADC channel 10 low byte','AR'), ...
    field(70,1,'ADC 10 (H)','ADC channel 10 high byte','AR'), ...
    field(71,2,'ADC 11','ADC channel 11','AR'), ...
    field(71,1,'ADC 11 (L)','ADC channel 11 low byte','AR'), ...
    field(72,1,'ADC 11 (H)','ADC channel 11 high byte','AR'), ...
    field(73,2,'ADC 12','ADC channel 12','AR'), ...
    field(73,1,'ADC 12 (L)','ADC channel 12 low byte','AR'), ...
    field(74,1,'ADC 12 (H)','ADC channel 12 high byte','AR'), ...
    field(75,2,'ADC 13','ADC channel 13','AR'), ...
    field(75,1,'ADC 13 (L)','ADC channel 13 low byte','AR'), ...
    field(76,1,'ADC 13 (H)','ADC channel 13 high byte','AR'), ...
    field(77,2,'ADC 14','ADC channel 14','AR'), ...
    field(77,1,'ADC 14 (L)','ADC channel 14 low byte','AR'), ...
    field(78,1,'ADC 14 (H)','ADC channel 14 high byte','AR'), ...
    field(79,2,'ADC 15','ADC channel 15','AR'), ...
    field(79,1,'ADC 15 (L)','ADC channel 15 low byte','AR'), ...
    field(80,1,'ADC 15 (H)','ADC channel 15 high byte','AR')
  };

ids = {
    id('Right Shoulder Pitch',1,200,315), ...
    id('Left Shoulder Pitch',2,270,315), ...
    id('Right Shoulder Roll',3,140,295), ...
    id('Left Shoulder Roll',4,325,295), ...
    id('Right Elbow',5,108,297), ...
    id('Left Elbow',6,360,297), ...
    id('Right Hip Yaw',7,200,250), ...
    id('Left Hip Yaw',8,270,250), ...
    id('Right Hip Roll',9,145,185), ...
    id('Left Hip Roll',10,325,185), ...
    id('Right Hip Pitch',11,200,185), ...
    id('Left Hip Pitch',12,265,185), ...
    id('Right Knee',13,200,125), ...
    id('Left Knee',14,265,125), ...
    id('Right Ankle Pitch',15,200,60), ...
    id('Left Ankle Pitch',16,265,60), ...
    id('Right Ankle Roll',17,140,50), ...
    id('Left Ankle Roll',18,330,50), ...
    id('Head Pan',19,235,310), ...
    id('Head Tilt',20,235,355), ...
    id('Sub controller',200,235,265) ...
  };
end

function s = field(address, size, name, description, mode)
s = struct('address', address, ...
           'size', size, ...
           'name', name, ...
           'description', description, ...
           'mode', mode);
end

function i = id(name,address,posx,posy)
i = struct('address', address, ...
           'name', name, ...
           'posx', posx, ...
           'posy', posy);
end

