function [mx28_fields,cm730_fields,fsr_fields,vision_fields,ids,labels,lang] = darwinop_consts_fr
mx28_fields = {
    field(0,2,'Modèle','Numéro de modèle','AR'), ...
    field(0,1,'Modèle (f)','Numéro de modèle (poids faible)','AR'), ...
    field(1,1,'Modèle (F)','Numéro de modèle (poids fort)','AR'), ...
    field(2,1,'Version','Information de version','AR'), ...
    field(3,1,'ID','ID du MX28 sur le bus Dynamixel','ARW'), ...
    field(4,1,'Débit binaire','Débit binaire du bus Dynamixel','ARW'), ...
    field(5,1,'Temps de retour','Temps de retour','ARW'), ...
    field(6,2,'Limite horaire','Limite angulaire dans le sens horaire','RW'), ...
    field(6,1,'Limite horaire (f)','Limite angulaire dans le sens horaire (poids faible)','ARW'), ...
    field(7,1,'Limite horaire (F)','Limite angulaire dans le sens horaire (poids fort)','ARW'), ...
    field(8,2,'Limite anti-horaire','Limite angulaire dans le sens anti-horaire','RW'), ...
    field(8,1,'Limite anti-horaire (f)','Limite angulaire dans le sens anti-horaire (poids faible)','ARW'), ...
    field(9,1,'Limite anti-horaire (F)','Limite angulaire dans le sens anti-horaire (poids fort)','ARW'), ...
    field(11,1,'Température maximale','Limite maximale de température','ARW'), ...
    field(12,1,'Tension minimale','Limite minimale de tension d''alimentation','ARW'), ...
    field(13,1,'Tension maximale','Limite maximale de tension d''alimentation','ARW'), ...
    field(14,2,'Couple maximal','Limite maximale de couple','ARW'), ...
    field(14,1,'Couple maximal (f)','Limite maximale de couple (poids faible)','ARW'), ...
    field(15,1,'Couple maximal (F)','Limite maximale de couple (poids fort)','ARW'), ...
    field(16,1,'Retour de statut','Configuration du retour automatique de statut','ARW'), ...
    field(17,1,'LED d''alarme','Configuration de la LED d''alarme','ARW'), ...
    field(18,1,'Mot d''erreur','Mot d''erreur','ARW'), ...
    field(24,1,'Activation du couple','Activation du couple','RW'), ...
    field(25,1,'LED','Allumage de la LED','RW'), ...
    field(26,1,'Gain D','Gain Dérivé','RW'), ...
    field(27,1,'Gain I','Gain Integral','RW'), ...
    field(28,1,'Gain P','Gain Proportionnel','RW'), ...
    field(30,2,'Consigne de position','Consigne de position','RW'), ...
    field(30,1,'Consigne de position (f)','Consigne de position (poids faible)','ARW'), ...
    field(31,1,'Consigne de position (F)','Consigne de position (poids fort)','ARW'), ...
    field(32,2,'Consigne de vitesse','Consigne de vitesse','RW'), ...
    field(32,1,'Consigne de vitesse (f)','Consigne de vitesse (poids faible)','ARW'), ...
    field(33,1,'Consigne de vitesse (F)','Consigne de vitesse (poids fort)','ARW'), ...
    field(34,2,'Limite de couple','Limite de couple','RW'), ...
    field(34,1,'Limite de couple (f)','Limite de couple (poids faible)','ARW'), ...
    field(35,1,'Limite de couple (F)','Limite de couple (poids fort)','ARW'), ...
    field(36,2,'Position courante','Retour de position','R'), ...
    field(36,1,'Position courante (f)','Retour de position (poids faible)','AR'), ...
    field(37,1,'Position courante (F)','Retour de position (poids fort)','AR'), ...
    field(38,2,'Vitesse courante','Retour de vitesse','R'), ...
    field(38,1,'Vitesse courante (f)','Retour de vitesse (poids faible)','AR'), ...
    field(39,1,'Vitesse courante (F)','Retour de vitesse (poids fort)','AR'), ...
    field(40,2,'Charge courante','Retour de charge','R'), ...
    field(40,1,'Charge courante (f)','Retour de charge (poids faible)','AR'), ...
    field(41,1,'Charge courante (F)','Retour de charge (poids fort)','AR'), ...
    field(42,1,'Tension','Tension d''alimentation','AR'), ...
    field(43,1,'Température','Température','AR'), ...
    field(44,1,'"Registered"','Instruction en cours "Registered"','AR'), ...
    field(46,1,'Déplacement','Déplacement en cours','AR'), ...
    field(47,1,'Verrouillage','Verrouillage de la mémoire EEPROM','ARW'), ...
    field(48,2,'Dépassement','Dépassement du couple maximal','ARW'), ...
    field(48,1,'Dépassement (f)','Dépassement du couple maximal (poids faible)','ARW'), ...
    field(49,1,'Dépassement (F)','Dépassement du couple maximal (poids fort)','ARW')
  };

cm730_fields = {
    field(0,2,'Modèle','Numéro de modèle','AR'), ...
    field(0,1,'Modèle (f)','Numéro de modèle (poids faible)','AR'), ...
    field(1,1,'Modèle (F)','Numéro de modèle (poids fort)','AR'), ...
    field(2,1,'Version','Information de version','AR'), ...
    field(3,1,'ID','ID du CM730 sur le bus Dynamixel','ARW'), ...
    field(4,1,'Débit binaire','Débit binaire du bus Dynamixel','ARW'), ...
    field(5,1,'Temps de retour','Temps de retour','ARW'), ...
    field(16,1,'Retour de statut','Configuration du retour automatique de statut','ARW'), ...
    field(24,1,'Activation du bus','Activation du bus Dynamixel','ARW'), ...
    field(25,1,'LED du panneau','Activation des LED du panneau','RW'), ...
    field(26,2,'LED de la tête','Activation des LED de la tête','RW'), ...
    field(26,1,'LED de la tête (f)','Activation des LED de la tête (poids faible)','ARW'), ...
    field(27,1,'LED de la tête (F)','Activation des LED de la tête (poids fort)','ARW'), ...
    field(28,2,'LED des yeux','Activation des LED des yeux','RW'), ...
    field(28,1,'LED des yeux (f)','Activation des LED des yeux (poids faible)','ARW'), ...
    field(29,1,'LED des yeux (F)','Activation des LED des yeux (poids fort)','ARW'), ...
    field(30,1,'Boutons','Etat des boutons','R'), ...
    field(38,2,'Gyro Z','Gyroscope axe Z','R'), ...
    field(38,1,'Gyro Z (f)','Gyroscope axe Z (poids faible)','AR'), ...
    field(39,1,'Gyro Z (F)','Gyroscope axe Z (poids fort)','AR'), ...
    field(40,2,'Gyro Y','Gyroscope axe Y','R'), ...
    field(40,1,'Gyro Y (f)','Gyroscope axe Y (poids faible)','AR'), ...
    field(41,1,'Gyro Y (F)','Gyroscope axe Y (poids fort)','AR'), ...
    field(42,2,'Gyro X','Gyroscope axe X','R'), ...
    field(42,1,'Gyro X (f)','Gyroscope axe X (poids faible)','AR'), ...
    field(43,1,'Gyro X (F)','Gyroscope axe X (poids fort)','AR'), ...
    field(44,2,'ACC X','Accéléromètre axe X','R'), ...
    field(44,1,'ACC X (f)','Accéléromètre axe X (poids faible)','AR'), ...
    field(45,1,'ACC X (F)','Accéléromètre axe X (poids fort)','AR'), ...
    field(46,2,'ACC Y','Accéléromètre axe Y','R'), ...
    field(46,1,'ACC Y (f)','Accéléromètre axe Y (poids faible)','AR'), ...
    field(47,1,'ACC Y (F)','Accéléromètre axe Y (poids fort)','AR'), ...
    field(48,2,'ACC Z','Accéléromètre axe Z','R'), ...
    field(48,1,'ACC Z (f)','Accéléromètre axe Z (poids faible)','AR'), ...
    field(49,1,'ACC Z (F)','Accéléromètre axe Z (poids fort)','AR'), ...
    field(50,1,'Tension','Tension d''alimentation','AR'), ...
    field(51,2,'Micro gauche','Microphone gauche','R'), ...
    field(51,1,'Micro gauche (f)','Microphone gauche (poids faible)','AR'), ...
    field(52,1,'Micro gauche (F)','Microphone gauche (poids fort)','AR'), ...
    field(53,2,'CAN 2','CAN canal 2','AR'), ...
    field(53,1,'CAN 2 (f)','CAN canal 2 (poids faible)','AR'), ...
    field(54,1,'CAN 2 (F)','CAN canal 2 (poids fort)','AR'), ...
    field(55,2,'CAN 3','ADC channel 3','AR'), ...
    field(55,1,'CAN 3 (f)','CAN canal 3 (poids faible)','AR'), ...
    field(56,1,'CAN 3 (F)','CAN canal 3 (poids fort)','AR'), ...
    field(57,2,'CAN 4','ADC channel 4','AR'), ...
    field(57,1,'CAN 4 (f)','CAN canal 4 (poids faible)','AR'), ...
    field(58,1,'CAN 4 (F)','CAN canal 4 (poids fort)','AR'), ...
    field(59,2,'CAN 5','ADC channel 5','AR'), ...
    field(59,1,'CAN 5 (f)','CAN canal 5 (poids faible)','AR'), ...
    field(60,1,'CAN 5 (F)','CAN canal 5 (poids fort)','AR'), ...
    field(61,2,'CAN 6','ADC channel 6','AR'), ...
    field(61,1,'CAN 6 (f)','CAN canal 6 (poids faible)','AR'), ...
    field(62,1,'CAN 6 (F)','CAN canal 6 (poids fort)','AR'), ...
    field(63,2,'CAN 7','ADC channel 7','AR'), ...
    field(63,1,'CAN 7 (f)','CAN canal 7 (poids faible)','AR'), ...
    field(64,1,'CAN 7 (F)','CAN canal 7 (poids fort)','AR'), ...
    field(65,2,'CAN 8','ADC channel 8','AR'), ...
    field(65,1,'CAN 8 (f)','CAN canal 8 (poids faible)','AR'), ...
    field(66,1,'CAN 8 (F)','CAN canal 8 (poids fort)','AR'), ...
    field(67,2,'Micro droit','Microphone droit','R'), ...
    field(67,1,'Micro droit (f)','Microphone droit (poids faible)','AR'), ...
    field(68,1,'Micro droit (F)','Microphone droit (poids fort)','AR'), ...
    field(69,2,'CAN 10','ADC channel 10','AR'), ...
    field(69,1,'CAN 10 (f)','CAN canal 10 (poids faible)','AR'), ...
    field(70,1,'CAN 10 (F)','CAN canal 10 (poids fort)','AR'), ...
    field(71,2,'CAN 11','ADC channel 11','AR'), ...
    field(71,1,'CAN 11 (f)','CAN canal 11 (poids faible)','AR'), ...
    field(72,1,'CAN 11 (F)','CAN canal 11 (poids fort)','AR'), ...
    field(73,2,'CAN 12','ADC channel 12','AR'), ...
    field(73,1,'CAN 12 (f)','CAN canal 12 (poids faible)','AR'), ...
    field(74,1,'CAN 12 (F)','CAN canal 12 (poids fort)','AR'), ...
    field(75,2,'CAN 13','ADC channel 13','AR'), ...
    field(75,1,'CAN 13 (f)','CAN canal 13 (poids faible)','AR'), ...
    field(76,1,'CAN 13 (F)','CAN canal 13 (poids fort)','AR'), ...
    field(77,2,'CAN 14','ADC channel 14','AR'), ...
    field(77,1,'CAN 14 (f)','CAN canal 14 (poids faible)','AR'), ...
    field(78,1,'CAN 14 (F)','CAN canal 14 (poids fort)','AR'), ...
    field(79,2,'CAN 15','ADC channel 15','AR'), ...
    field(79,1,'CAN 15 (f)','CAN canal 15 (poids faible)','AR'), ...
    field(80,1,'CAN 15 (F)','CAN canal 15 (poids fort)','AR')
  };

fsr_fields = {
    field(0,2,'Modèle','Numéro de modèle','AR'), ...
    field(0,1,'Modèle (f)','Numéro de modèle (poids faible)','AR'), ...
    field(1,1,'Modèle (F)','Numéro de modèle (poids fort)','AR'), ...
    field(2,1,'Version','Information de version','AR'), ...
    field(3,1,'ID','ID du FSR sur le bus Dynamixel','ARW'), ...
    field(4,1,'Débit binaire','Débit binaire du bus Dynamixel','ARW'), ...
    field(5,1,'Temps de retour','Temps de retour','ARW'), ...
    field(16,1,'Retour de statut','Configuration du retour automatique de statut','ARW'), ...
    field(19,1,'Mode','Mode de fonctionnement','RW'), ...
    field(25,1,'LED','Allumage de la LED','RW'), ...
    field(26,2,'Jauge 1','Jauge de déformation 1','R'), ...
    field(26,1,'Jauge 1 (f)','Jauge de déformation 1 (poids faible)','AR'), ...
    field(27,1,'Jauge 1 (F)','Jauge de déformation 1 (poids fort)','AR'), ...
    field(28,2,'Jauge 2','Jauge de déformation 2','R'), ...
    field(28,1,'Jauge 2 (f)','Jauge de déformation 2 (poids faible)','AR'), ...
    field(29,1,'Jauge 2 (F)','Jauge de déformation 2 (poids fort)','AR'), ...
    field(30,2,'Jauge 3','Jauge de déformation 3','R'), ...
    field(30,1,'Jauge 3 (f)','Jauge de déformation 3 (poids faible)','AR'), ...
    field(31,1,'Jauge 3 (F)','Jauge de déformation 3 (poids fort)','AR'), ...
    field(32,2,'Jauge 4','Jauge de déformation 4','R'), ...
    field(32,1,'Jauge 4 (f)','Jauge de déformation 4 (poids faible)','AR'), ...
    field(33,1,'Jauge 4 (F)','Jauge de déformation 4 (poids fort)','AR'), ...
    field(34,1,'Jauge X','Jauge de déformation (axe X)','R'), ...
    field(35,1,'Jauge Y','Jauge de déformation (axe Y)','R'), ...
    field(42,1,'Tension','Tension d''alimentation','AR'), ...
    field(44,1,'"Registered"','Instruction en cours "Registered"','AR'), ...
    field(47,1,'Verrouillage','Verrouillage de la mémoire EEPROM','ARW'), ...
  };

vision_fields = {
    field(1,1,'Activation','Activation de la vision','RW'), ...
    field(2,2,'Largeur','Largeur de la caméra en pixels','R'), ...
    field(4,2,'Hauteur','Hauteur de la caméra en pixels','R'), ...
    field(6,1,'Balle: activation','Activation de la reconnaissance de la balle','RW'), ...
    field(7,1,'Rouge: activation','Activation de la reconnaissance de la zone rouge','RW'), ...
    field(8,1,'Jaune: activation','Activation de la reconnaissance de la zone jaune','RW'), ...
    field(9,1,'Bleu: activation','Activation de la reconnaissance de la zone bleue','RW'), ...
    field(10,1,'Diffusion','Diffusion des images sur le serveur HTTP','RW'), ...
    field(20,2,'Balle: teinte cen.','Valeur centrale de la teinte de la balle','RW'), ...
    field(22,2,'Balle: teinte tol.','Tolérance sur la teinte de la balle','RW'), ...
    field(24,1,'Balle: sat. min.','Seuil minimal sur la saturation de la balle','ARW'), ...
    field(25,1,'Balle: sat. max.','Seuil maximal sur la saturation de la balle','ARW'), ...
    field(26,1,'Balle: val. min.','Seuil minimal sur la valeur de la balle','ARW'), ...
    field(27,1,'Balle: val. max.','Seuil maximal sur la valeur de la balle','ARW'), ...
    field(28,1,'Balle: couv. min.','Seuil minimal sur la couverture de la balle','ARW'), ...
    field(29,1,'Balle: couv. max.','Seuil maximal sur la couverture de la balle','ARW'), ...
    field(30,2,'Balle: X','Position X de la balle','R'), ...
    field(32,2,'Balle: Y','Position Y de la balle','R'), ...
    field(40,2,'Rouge: teinte cen.','Valeur centrale de la teinte de la zone rouge','RW'), ...
    field(42,2,'Rouge: teinte tol.','Tolérance sur la teinte de la zone rouge','RW'), ...
    field(44,1,'Rouge: sat. min.','Seuil minimal sur la saturation de la zone rouge','ARW'), ...
    field(45,1,'Rouge: sat. max.','Seuil maximal sur la saturation de la zone rouge','ARW'), ...
    field(46,1,'Rouge: val. min.','Seuil minimal sur la valeur de la zone rouge','ARW'), ...
    field(47,1,'Rouge: val. max.','Seuil maximal sur la valeur de la zone rouge','ARW'), ...
    field(48,1,'Rouge: couv. min.','Seuil minimal sur la couverture de la zone rouge','ARW'), ...
    field(49,1,'Rouge: couv. max.','Seuil maximal sur la couverture de la zone rouge','ARW'), ...
    field(50,2,'Rouge: X','Position X de la zone rouge','R'), ...
    field(52,2,'Rouge: Y','Position Y de la zone rouge','R'), ...
    field(60,2,'Jaune: teinte cen.','Valeur centrale de la teinte de la zone jaune','RW'), ...
    field(62,2,'Jaune: teinte tol.','Tolérance sur la teinte de la zone jaune','RW'), ...
    field(64,1,'Jaune: sat. min.','Seuil minimal sur la saturation de la zone jaune','ARW'), ...
    field(65,1,'Jaune: sat. max.','Seuil maximal sur la saturation de la zone jaune','ARW'), ...
    field(66,1,'Jaune: val. min.','Seuil minimal sur la valeur de la zone jaune','ARW'), ...
    field(67,1,'Jaune: val. max.','Seuil maximal sur la valeur de la zone jaune','ARW'), ...
    field(68,1,'Jaune: couv. min.','Seuil minimal sur la couverture de la zone jaune','ARW'), ...
    field(69,1,'Jaune: couv. max.','Seuil maximal sur la couverture de la zone jaune','ARW'), ...
    field(70,2,'Jaune: X','Position X de la zone jaune','R'), ...
    field(72,2,'Jaune: Y','Position Y de la zone jaune','R'), ...
    field(80,2,'Bleu: teinte cen.','Valeur centrale de la teinte de la zone bleue','RW'), ...
    field(82,2,'Bleu: teinte tol.','Tolérance sur la teinte de la zone bleue','RW'), ...
    field(84,1,'Bleu: sat. min.','Seuil minimal sur la saturation de la zone bleue','ARW'), ...
    field(85,1,'Bleu: sat. max.','Seuil maximal sur la saturation de la zone bleue','ARW'), ...
    field(86,1,'Bleu: val. min.','Seuil minimal sur la valeur de la zone bleue','ARW'), ...
    field(87,1,'Bleu: val. max.','Seuil maximal sur la valeur de la zone bleue','ARW'), ...
    field(88,1,'Bleu: couv. min.','Seuil minimal sur la couverture de la zone bleue','ARW'), ...
    field(89,1,'Bleu: couv. max.','Seuil maximal sur la couverture de la zone bleue','ARW'), ...
    field(90,2,'Bleu: X','Position X de la zone bleue','R'), ...
    field(92,2,'Bleu: Y','Position Y de la zone bleue','R'), ...
  };

ids = {
    id('Épaule droite (tangage)',1,200,315), ...
    id('Épaule gauche (tangage)',2,270,315), ...
    id('Épaule droite (roulis)',3,140,295), ...
    id('Épaule gauche (roulis)',4,325,295), ...
    id('Coude droit',5,108,297), ...
    id('Coude gauche',6,360,297), ...
    id('Hanche droite (lacet)',7,200,250), ...
    id('Hanche gauche (lacet)',8,270,250), ...
    id('Hanche droite (roulis)',9,145,185), ...
    id('Hanche gauche (roulis)',10,325,185), ...
    id('Hanche droite (tangage)',11,200,185), ...
    id('Hanche gauche (tangage)',12,265,185), ...
    id('Genou droit',13,200,125), ...
    id('Genou gauche',14,265,125), ...
    id('Cheville droite (tangage)',15,200,60), ...
    id('Cheville gauche (tangage)',16,265,60), ...
    id('Cheville droite (roulis)',17,140,50), ...
    id('Cheville gauche (roulis)',18,330,50), ...
    id('Tête (lacet)',19,235,310), ...
    id('Tête (tangage)',20,235,355), ...
    id('Sous contrôleur',200,235,265) ...
    id('Pied droit',111,200,20), ...
    id('Pied gauche',112,265,20), ...
    id('Vision',-1,225,380), ...
  };
  labels = {
    'Configuration de la communication avec le Darwin-OP (%s)', ...
    'Données à lire (ctrl+click pour multiples):', ...
    'Données à écrire (ctrl+click pour multiples):', ...
    'Sélection', ...
    'Lecture/écriture', ...
    'Écriture', ...
    'Lecture', ...
    'Pas d''opération', ...
    'Adresse IP :', ...
    'Port :', ...
    'Protocole :', ...
    'Période d''éch.(s):', ...
    'Configuration avancée', ...
    'Valider et fermer', ...
  };
  lang = 'français';
end

function s = field(address, size, name, description, mode)
s = struct('address', address, ...
           'size', size, ...
           'name', name, ...
           'description', description, ...
           'mode', mode);
end

function i = id(name,address,posx,posy)
i = struct('address', address, ...
           'name', name, ...
           'posx', posx, ...
           'posy', posy);
end
